# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/elevate-climate',
                'doc_host': 'https://BrandonChiazza.github.io',
                'git_url': 'https://github.com/BrandonChiazza/elevate-climate',
                'lib_path': 'elevate_climate'},
  'syms': {'elevate_climate.core': {'elevate_climate.core.foo': ('core.html#foo', 'elevate_climate/core.py')}}}
